# Generated by Django 5.0.8 on 2024-08-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('roll', models.DecimalField(decimal_places=0, max_digits=3)),
                ('department', models.CharField(max_length=60)),
                ('notes', models.TextField()),
            ],
        ),
    ]
